notify

diff --git a/notify b/notify
--- a/notify
+++ b/notify
@@ -1,6 +1,146 @@
 #!/bin/sh
+# Send a message to za3k
+# Feel free to use during reasonable hours to contact me.
+# =============== config ===============
+NAME=notify2zak
+
+EMAIL=za3k@za3k.com
+
+NTFY_CHANNEL=za3k_general
+
+# Google voice does not support this
+# Good2Go does!
+PHONE_EMAIL=5106978728@txt.att.net
+
+# Always sent using my ZNC bouncer, which requires my laptop that stores the password
+IRC_NICK=za3k
+IRC_SERVER=libera.znc.za3k.com:10000
+
+TZ=EST5EDT
+# =============== code ===============
+SENDMAIL=sendmail
+if which sendmail 2>/dev/null >/dev/null; then :; else SENDMAIL=/usr/lib/sendmail; fi
+
 email() {
- echo "Subject: $1" | /usr/lib/sendmail -v za3k@za3k.com
+    echo "Subject: $NAME $1" | $SENDMAIL $EMAIL
 }
 
-email "$1"
+ntfy() {
+    curl -s -d "$NAME: $1" ntfy.sh/$NTFY_CHANNEL >/dev/null
+}
+
+popup() {
+    LOCAL_COMMAND=( notify-send "$NAME" -t 10000000 "$1" )
+    REMOTE_COMMAND="notify-send '$NAME' -t 10000000 '$1'"
+    case `hostname` in
+        juice)
+            "${LOCAL_COMMAND[@]}"
+            ssh laptop "$REMOTE_COMMAND"
+        ;;
+        rosemary)
+            "${LOCAL_COMMAND[@]}"
+            ssh juice "$REMOTE_COMMAND"
+        ;;
+        *) ssh juice notify --popup "$1" ;;
+    esac
+}
+
+speak() {
+  if [ -z "$XDG_RUNTIME_DIR" ]; then
+    export XDG_RUNTIME_DIR="/run/user/`id -u`"
+  fi
+  case `hostname` in
+    germinate|juice|rosemary)
+        if which say 2>/dev/null >/dev/null; then
+            say "$1"
+        fi
+        ;;
+    *) ;;
+  esac
+  case `hostname` in
+    germinate|rosemary) ssh juice say "$1" ;;
+    juice) ;;
+    *) reasonable_time && ssh juice say "$1" ;;
+  esac
+}
+
+irc() {
+    case `hostname` in
+      rosemary)
+        [ `hostname` == rosemary ] || return 0
+        IRC_HOST="$(echo "$IRC_SERVER" | cut -f1 -d:)"
+        IRC_PORT="$(echo "$IRC_SERVER" | cut -f2 -d:)"
+        IRC_PASSWORD=`grep "kisspunch/libera" .purple/accounts.xml | sed "s/.*>\(.*\)<.*/\1/"`
+        { 
+            echo "PASS $IRC_PASSWORD"
+            echo "NICK kisspunch"
+            echo "USER kisspunch@libera.znc.za3k.com 0 * :kisspunch"
+            echo "PRIVMSG $IRC_NICK :$NAME: $1"
+            echo "QUIT"
+        } | /usr/bin/gnutls-cli --no-ca-verification -p $IRC_PORT $IRC_HOST >/dev/null 2>/dev/null
+        ;;
+      juice)
+        # Sorry future self
+        ssh laptop /home/zachary/.projects/short-programs/notify --irc "$1"
+        ;;
+      *)
+        ssh juice notify --irc "$1"
+        ;;
+    esac
+}
+
+sms() {
+    echo "Subject: $NAME $1" | $SENDMAIL $PHONE_EMAIL
+}
+
+usage() {
+    echo "Usage: notify --afk <MESSAGE>:  Send a notification to zak" >&2
+    echo "       notify --here <MESSAGE>: Send a notification to zak" >&2
+    echo "       notify --push" >&2
+}
+
+reasonable_time() {
+    case `\date "+%H"` in
+        01|02|03|04|05|06|07|08|09|10)
+            echo "No. It's an unreasonable time of day to contact me." >&2
+            return 1
+            ;;
+        *)
+            return 0
+    esac
+}
+
+case "$1" in
+  --speak)  speak "$2" ;;
+  --popup)  popup "$2" ;;
+  --sms)    sms "$2" ;;
+  --email)  email "$2" ;;
+  --ntfy)   ntfy "$2" ;;
+  --irc)    irc "$2" ;;
+  --here)
+            popup "$2"
+            speak "$2"
+    ;&
+  --afk)
+            email "$2"
+            ntfy "$2"
+            sms "$2"
+            irc "$2"
+    ;;
+  --push)
+    if [ `hostname` != 'rosemary' ]; then
+        echo "Wrong machine." >&2
+        exit 1
+    fi
+    exe="$0"
+    for machine in germinate deadtree juice; do
+        echo -n "${machine}... "
+        rsync --rsync-path="sudo rsync" "$exe" $machine:/bin/notify && echo "pushed" || echo "FAILED"
+    done
+    echo -n "tron... "
+    rsync "$exe" tron:bin/notify2zak && echo "pushed" || echo "FAILED"
+    ;;
+  *)
+    usage
+    ;;
+esac
